name: dependency_validator
version: 2.0.1
description: Checks for missing, under-promoted, over-promoted, and unused dependencies.
homepage: https://github.com/Workiva/dependency_validator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  build_config: ^0.4.7
  checked_yaml: ^2.0.1
  glob: ^2.0.0
  json_annotation: ^4.0.0
  logging: ^1.0.0
  package_config: ^2.0.0
  path: ^1.8.0
  pub_semver: ^2.0.0
  pubspec_parse: ^1.0.0
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^1.11.0
  json_serializable: ^4.0.0
  test: ^1.16.0
  test_descriptor: ^2.0.0
  workiva_analysis_options: ^1.2.0

executables:
  dependency_validator:

dependency_validator:
  ignore:
    - json_serializable
    - _foo
    - foo
    - _bar
    - bar
    - foo1
    - foo_foo
